version: "3.7"
services:
  web:
    image: nginx
    deploy:
      replicas: 5
      resouces:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webserver
networks:
  webserver:
